modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="maltinmysticism"
version="1.0.0"
displayName="MaltinMysticism"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="JohnWillStab, MCreator"

[[dependencies.maltinmysticism]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




